### ISSUE TITLE
Consider renaming zcl_wd_color_util

### ISSUE THREAD

**Issue by abap-weasel** [thedoginthewok/abapMermaid#2]
All other repository objects has "mermaid" in name, but zcl_wd_color_util has potential to result in conflict when target system already has object with that name. Consider adding "mermaid" to its name.

**Comment by WegnerDan** [comment]
Yeah, that class is a snippet that I wrote and copy paste when needed. 
I will rename it

**Comment by WegnerDan** [comment]
Fixed with https://github.com/thedoginthewok/abapMermaid/commit/3aa887b2a0a4f8e4a8e2ba20b3abd1a7d23c2064
